name = "vibefly-ai"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[vars]
FROM_EMAIL = "noreply@vibefly.ai"
OWNER_EMAIL = "emcweeney@gmail.com"

[assets]
directory = "./htdocs"
binding = "ASSETS"

[env.dev]
name = "vibefly-ai-dev"

[env.dev.vars]
FROM_EMAIL = "noreply@vibefly.ai"
OWNER_EMAIL = "emcweeney@gmail.com"
